name: compile
on:
  workflow_dispatch:
#  schedule:
#      - cron: '55 */5 * * *'
jobs:
  runner1:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: download-and-run
        run: |
              make
              sudo make install
              mv /usr/local/bin/massdns .
              git config --global user.email "some-secret@secret.com"
              git config --global user.name "Actions"
              git add --all 
              git commit -m "compiled"
              git push origin master 
